version: '3'
services:
 website:
  image: php:apache
  ports:
  -"80:80"
  environment:
   USERNAME: diyama
   PASSWORD: 306826
  volumes:
   - "./website:/var/www/html"
  depends_on:
   - API
  restart: always
 API:
  image: studentlistapi
  ports :
   - "5000:5000"
  volumes:
   -"/data:/data"
  restart: always
